import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { generateText, Output } from "ai";
import { z } from "zod";
import { createLovableAiGatewayProvider } from "@/lib/ai-gateway";

const companySchema = z.object({
  industry: z.string(),
  stage: z.string(),
  employees: z.number().int().min(0),
  employeeGrowth: z.string(),
  funding: z.string(),
  hq: z.string(),
  techStack: z.array(z.string()).max(12),
  icpScore: z.number().int().min(0).max(100),
  whyNow: z.string(),
  riskFlags: z.array(z.string()).max(6),
  strategy: z.array(z.string()).max(6),
});

const personSchema = z.object({
  name: z.string(),
  title: z.string(),
  role: z.enum(["Economic Buyer", "Champion", "Influencer", "Blocker", "End User"]),
  influence: z.number().int().min(1).max(5),
  sentiment: z.enum(["positive", "neutral", "negative", "unknown"]),
  copy: z.object({
    context: z.string(),
    emailSubject: z.string(),
    emailBody: z.string(),
    linkedinDm: z.string(),
    callScript: z.string(),
    aiRecs: z.array(z.string()).max(6),
    voicemailScript: z.string(),
  }),
});

export const enrichEntity = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d: unknown) =>
    z
      .object({
        kind: z.enum(["company", "person"]),
        query: z.string().min(1).max(280),
        linkedinUrl: z.string().max(280).optional(),
        companyContext: z.string().max(500).optional(),
      })
      .parse(d)
  )
  .handler(async ({ data }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) throw new Error("Missing LOVABLE_API_KEY");
    const gateway = createLovableAiGatewayProvider(key);
    const model = gateway("google/gemini-3-flash-preview");

    const baseRule =
      "You are a B2B sales research assistant. Generate plausible, structured intel for a sales DealRoom. " +
      "Be concrete, sales-ready, and avoid disclaimers. Generated by AI — the user will verify before acting.";

    if (data.kind === "company") {
      const prompt = `${baseRule}\n\nResearch this company and return enriched firmographics + GTM intel.\n` +
        `Query: ${data.query}\n` +
        (data.linkedinUrl ? `LinkedIn: ${data.linkedinUrl}\n` : "") +
        `Return industry, funding stage, employee count, growth %, funding round (e.g. "Series B — $40M"), ` +
        `HQ city/state, top 5 likely tech stack tools, ICP fit score 0-100, a sharp "why now" (1-2 sentences), ` +
        `up to 4 risk flags, and up to 5 strategy bullets.`;
      try {
        const { experimental_output } = await generateText({
          model,
          prompt,
          experimental_output: Output.object({ schema: companySchema }),
        });
        return { kind: "company" as const, data: experimental_output };
      } catch (e) {
        const msg = (e as Error).message ?? "AI request failed";
        if (msg.includes("429")) throw new Error("AI rate limit hit. Try again in a moment.");
        if (msg.includes("402")) throw new Error("AI credits exhausted. Add credits in Settings.");
        throw new Error(msg);
      }
    }

    const prompt = `${baseRule}\n\nResearch this person and return a stakeholder profile + outreach copy.\n` +
      `Query: ${data.query}\n` +
      (data.linkedinUrl ? `LinkedIn: ${data.linkedinUrl}\n` : "") +
      (data.companyContext ? `Company context: ${data.companyContext}\n` : "") +
      `Return name, title, sales role (Economic Buyer / Champion / Influencer / Blocker / End User), ` +
      `influence 1-5, sentiment guess, and a copy pack: context (2 sentences), emailSubject, emailBody (3-5 lines), ` +
      `linkedinDm (2-3 lines), callScript (5-8 lines), 3 aiRecs, voicemailScript (3 lines).`;
    try {
      const { experimental_output } = await generateText({
        model,
        prompt,
        experimental_output: Output.object({ schema: personSchema }),
      });
      return { kind: "person" as const, data: experimental_output };
    } catch (e) {
      const msg = (e as Error).message ?? "AI request failed";
      if (msg.includes("429")) throw new Error("AI rate limit hit. Try again in a moment.");
      if (msg.includes("402")) throw new Error("AI credits exhausted. Add credits in Settings.");
      throw new Error(msg);
    }
  });
