import { useState } from "react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Sparkles, Loader2, Check } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { enrichEntity } from "@/lib/enrich.functions";
import { toast } from "sonner";
import type { Company } from "@/types";

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  company: Company;
  onApply: (patch: Record<string, unknown>) => Promise<void> | void;
}

export function EnrichDrawer({ open, onOpenChange, company, onApply }: Props) {
  const enrich = useServerFn(enrichEntity);
  const [query, setQuery] = useState(company.name);
  const [linkedin, setLinkedin] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<null | {
    industry: string; stage: string; employees: number; employeeGrowth: string; funding: string;
    hq: string; techStack: string[]; icpScore: number; whyNow: string; riskFlags: string[]; strategy: string[];
  }>(null);

  const run = async () => {
    setLoading(true);
    setResult(null);
    try {
      const res = await enrich({ data: { kind: "company", query, linkedinUrl: linkedin || undefined } });
      if (res.kind === "company") setResult(res.data);
    } catch (e) {
      toast.error("Enrichment failed", { description: (e as Error).message });
    } finally {
      setLoading(false);
    }
  };

  const apply = async () => {
    if (!result) return;
    await onApply({
      industry: result.industry,
      stage: result.stage,
      employees: result.employees,
      employee_growth: result.employeeGrowth,
      funding: result.funding,
      hq: result.hq,
      tech_stack: result.techStack,
      icp_score: result.icpScore,
      why_now: result.whyNow,
      risk_flags: result.riskFlags,
      strategy: result.strategy,
    });
    toast.success("Enrichment applied");
    onOpenChange(false);
    setResult(null);
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-[440px] sm:w-[540px] sm:max-w-none overflow-y-auto bg-card border-border">
        <SheetHeader>
          <SheetTitle className="font-display flex items-center gap-2"><Sparkles className="w-4 h-4 text-primary" /> Enrich with AI</SheetTitle>
          <SheetDescription className="text-xs">Generated by AI — verify before acting on it.</SheetDescription>
        </SheetHeader>
        <div className="space-y-3 mt-5">
          <div>
            <label className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">Company name or topic</label>
            <Input value={query} onChange={(e) => setQuery(e.target.value)} className="mt-1.5 bg-surface border-border" />
          </div>
          <div>
            <label className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">LinkedIn URL (optional)</label>
            <Input value={linkedin} onChange={(e) => setLinkedin(e.target.value)} placeholder="linkedin.com/company/..." className="mt-1.5 bg-surface border-border" />
          </div>
          <Button onClick={run} disabled={loading || !query.trim()} className="w-full" style={{ background: "var(--gradient-primary)" }}>
            {loading ? <><Loader2 className="w-3.5 h-3.5 mr-2 animate-spin" /> Enriching…</> : <><Sparkles className="w-3.5 h-3.5 mr-2" /> Generate</>}
          </Button>
        </div>

        {result && (
          <div className="mt-6 space-y-4 border-t border-border pt-5">
            <div className="text-[10px] font-mono uppercase tracking-wider text-primary">Proposed enrichment</div>
            {[
              ["Industry", result.industry],
              ["Stage", result.stage],
              ["Employees", `${result.employees} (${result.employeeGrowth})`],
              ["Funding", result.funding],
              ["HQ", result.hq],
              ["Tech stack", result.techStack.join(", ")],
              ["ICP score", String(result.icpScore)],
            ].map(([k, v]) => (
              <div key={k} className="text-xs">
                <div className="font-mono uppercase tracking-wider text-muted-foreground text-[10px]">{k}</div>
                <div className="mt-0.5">{v}</div>
              </div>
            ))}
            <div className="text-xs">
              <div className="font-mono uppercase tracking-wider text-muted-foreground text-[10px]">Why now</div>
              <p className="mt-0.5 leading-relaxed">{result.whyNow}</p>
            </div>
            {result.riskFlags.length > 0 && (
              <div className="text-xs">
                <div className="font-mono uppercase tracking-wider text-destructive text-[10px]">Risks</div>
                <ul className="mt-1 space-y-1">{result.riskFlags.map((r, i) => <li key={i}>⚠️ {r}</li>)}</ul>
              </div>
            )}
            {result.strategy.length > 0 && (
              <div className="text-xs">
                <div className="font-mono uppercase tracking-wider text-accent text-[10px]">Strategy</div>
                <ul className="mt-1 space-y-1">{result.strategy.map((s, i) => <li key={i}>→ {s}</li>)}</ul>
              </div>
            )}
            <Button onClick={apply} className="w-full" style={{ background: "var(--gradient-primary)" }}>
              <Check className="w-3.5 h-3.5 mr-2" /> Apply to DealRoom
            </Button>
          </div>
        )}
      </SheetContent>
    </Sheet>
  );
}
