/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoDealroomRouteImport } from './routes/demo.dealroom'
import { Route as AppTouchpointsRouteImport } from './routes/app.touchpoints'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppStakeholdersRouteImport } from './routes/app.stakeholders'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppDealroomsRouteImport } from './routes/app.dealrooms'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppDealroomsIdRouteImport } from './routes/app.dealrooms.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDealroomRoute = DemoDealroomRouteImport.update({
  id: '/demo/dealroom',
  path: '/demo/dealroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTouchpointsRoute = AppTouchpointsRouteImport.update({
  id: '/touchpoints',
  path: '/touchpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppStakeholdersRoute = AppStakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDealroomsRoute = AppDealroomsRouteImport.update({
  id: '/dealrooms',
  path: '/dealrooms',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDealroomsIdRoute = AppDealroomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDealroomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/team': typeof AppTeamRoute
  '/app/touchpoints': typeof AppTouchpointsRoute
  '/demo/dealroom': typeof DemoDealroomRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/team': typeof AppTeamRoute
  '/app/touchpoints': typeof AppTouchpointsRoute
  '/demo/dealroom': typeof DemoDealroomRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/chat': typeof ApiChatRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stakeholders': typeof AppStakeholdersRoute
  '/app/team': typeof AppTeamRoute
  '/app/touchpoints': typeof AppTouchpointsRoute
  '/demo/dealroom': typeof DemoDealroomRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/analytics'
    | '/app/automations'
    | '/app/dealrooms'
    | '/app/integrations'
    | '/app/intelligence'
    | '/app/overview'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/team'
    | '/app/touchpoints'
    | '/demo/dealroom'
    | '/app/dealrooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/analytics'
    | '/app/automations'
    | '/app/dealrooms'
    | '/app/integrations'
    | '/app/intelligence'
    | '/app/overview'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/team'
    | '/app/touchpoints'
    | '/demo/dealroom'
    | '/app/dealrooms/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/chat'
    | '/app/analytics'
    | '/app/automations'
    | '/app/dealrooms'
    | '/app/integrations'
    | '/app/intelligence'
    | '/app/overview'
    | '/app/settings'
    | '/app/stakeholders'
    | '/app/team'
    | '/app/touchpoints'
    | '/demo/dealroom'
    | '/app/dealrooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiChatRoute: typeof ApiChatRoute
  DemoDealroomRoute: typeof DemoDealroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dealroom': {
      id: '/demo/dealroom'
      path: '/demo/dealroom'
      fullPath: '/demo/dealroom'
      preLoaderRoute: typeof DemoDealroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/touchpoints': {
      id: '/app/touchpoints'
      path: '/touchpoints'
      fullPath: '/app/touchpoints'
      preLoaderRoute: typeof AppTouchpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stakeholders': {
      id: '/app/stakeholders'
      path: '/stakeholders'
      fullPath: '/app/stakeholders'
      preLoaderRoute: typeof AppStakeholdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dealrooms': {
      id: '/app/dealrooms'
      path: '/dealrooms'
      fullPath: '/app/dealrooms'
      preLoaderRoute: typeof AppDealroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dealrooms/$id': {
      id: '/app/dealrooms/$id'
      path: '/$id'
      fullPath: '/app/dealrooms/$id'
      preLoaderRoute: typeof AppDealroomsIdRouteImport
      parentRoute: typeof AppDealroomsRoute
    }
  }
}

interface AppDealroomsRouteChildren {
  AppDealroomsIdRoute: typeof AppDealroomsIdRoute
}

const AppDealroomsRouteChildren: AppDealroomsRouteChildren = {
  AppDealroomsIdRoute: AppDealroomsIdRoute,
}

const AppDealroomsRouteWithChildren = AppDealroomsRoute._addFileChildren(
  AppDealroomsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppDealroomsRoute: typeof AppDealroomsRouteWithChildren
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStakeholdersRoute: typeof AppStakeholdersRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTouchpointsRoute: typeof AppTouchpointsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAutomationsRoute: AppAutomationsRoute,
  AppDealroomsRoute: AppDealroomsRouteWithChildren,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStakeholdersRoute: AppStakeholdersRoute,
  AppTeamRoute: AppTeamRoute,
  AppTouchpointsRoute: AppTouchpointsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiChatRoute: ApiChatRoute,
  DemoDealroomRoute: DemoDealroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
