/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppDealroomsRouteImport } from './routes/app.dealrooms'
import { Route as AppDealroomsIdRouteImport } from './routes/app.dealrooms.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDealroomsRoute = AppDealroomsRouteImport.update({
  id: '/dealrooms',
  path: '/dealrooms',
  getParentRoute: () => AppRoute,
} as any)
const AppDealroomsIdRoute = AppDealroomsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDealroomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/dealrooms': typeof AppDealroomsRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/dealrooms/$id': typeof AppDealroomsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dealrooms'
    | '/app/overview'
    | '/app/dealrooms/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/dealrooms' | '/app/overview' | '/app/dealrooms/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/dealrooms'
    | '/app/overview'
    | '/app/dealrooms/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dealrooms': {
      id: '/app/dealrooms'
      path: '/dealrooms'
      fullPath: '/app/dealrooms'
      preLoaderRoute: typeof AppDealroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dealrooms/$id': {
      id: '/app/dealrooms/$id'
      path: '/$id'
      fullPath: '/app/dealrooms/$id'
      preLoaderRoute: typeof AppDealroomsIdRouteImport
      parentRoute: typeof AppDealroomsRoute
    }
  }
}

interface AppDealroomsRouteChildren {
  AppDealroomsIdRoute: typeof AppDealroomsIdRoute
}

const AppDealroomsRouteChildren: AppDealroomsRouteChildren = {
  AppDealroomsIdRoute: AppDealroomsIdRoute,
}

const AppDealroomsRouteWithChildren = AppDealroomsRoute._addFileChildren(
  AppDealroomsRouteChildren,
)

interface AppRouteChildren {
  AppDealroomsRoute: typeof AppDealroomsRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDealroomsRoute: AppDealroomsRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
